#!/bin/bash

currdate=$(date +%Y.%m.%d)
echo -e "current date: $currdate\n"

# get latest tag matching the pattern YYYY.MM.DD.*
latest_tag=$(git tag -l "${currdate}.*" | grep -v '^latest$' | sort -V | tail -n 1)
echo "latest tag: $latest_tag"

#if it doesnt exist make it
if [ -z "$latest_tag" ]; then
  newversion="${currdate}.0"
else #if it exists increment it
  oldincrement=$(echo "$latest_tag" | awk -F'.' '{print $4}')
  newversion="${currdate}.$((oldincrement + 1))"
fi

echo -e "newversion: $newversion\n"

# create and push the new tag
git tag "$newversion"
git push origin "$newversion"


printf $newversion > version

# optional: use the version in build steps
./build_script
./build_extension

