#!/bin/bash
#Build from src/, save to builds/
source="src/"
destination="builds/extension/"
mkdir -p $destination
output=$(web-ext build --source-dir="$source" --artifacts-dir="$destination" --overwrite-dest)

mv "$destination"/*.zip "$destination"/spotifyimmersive-latest.xpi
#mv "$newfile" "${newfile%.zip}.xpi"
