name: Auto Publish Latest Main Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create or update releases

    steps:
      - uses: actions/checkout@v4
      
      - name: Install web-ext
        run: npm install -g web-ext
        
      - name: Make autoversion executable
        run: |
            chmod +x ./autoversion
            chmod +x ./build_extension
            chmod +x ./build_script
        
      - name: Build with current version
        run: ./autoversion
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # this is required to fetch tags
          fetch-tags: true
          
      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "latest v${{ steps.get_version.outputs.version }}"
          files: |
            ./builds/script/spotifyimmersive_tampermonkey.js
            ./builds/extension/spotifyimmersive-latest.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
