name: Auto Publish Latest Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create or update releases

    steps:
      - uses: actions/checkout@v4
      
      - name: Install web-ext
        run: npm install -g web-ext
        
      - name: Make autoversion executable
        run: |
            chmod +x ./autoversion
            chmod +x ./build_extension
            chmod +x ./build_script
        
      - name: Increment version and build
        run: ./build_extension
        
      - name: Read version from file
        id: get_version
        run: |
          VERSION=$(cat version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "latest v${{ steps.get_version.outputs.version }}"
          files: |
            ./builds/script/spotifyimmersive_tampermonkey.js
            ./builds/extension/spotifyimmersive-latest.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
