name: Auto Publish Latest Main Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create or update releases
    env:
      AUTOVERSION_PATH: .github/workflows/scripts/autoversion
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # this is required to fetch tags
          fetch-tags: true
          
      - name: Install web-ext
        run: npm install -g web-ext
        
      - name: Make scripts executable
        run: |
            chmod +x $AUTOVERSION_PATH
            chmod +x ./getversion
            chmod +x ./build_extension
            chmod +x ./build_script
        
      - name: Increment version and build files
        run: $AUTOVERSION_PATH
      
      - name: Get version
        id: get_version
        run: echo "version=$(./getversion)" >> $GITHUB_OUTPUT
  
      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "latest v${{ steps.get_version.outputs.version }}"
          files: |
            ./builds/script/spotifyimmersive_tampermonkey.js
            ./builds/extension/spotifyimmersive-latest.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
