name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create or update releases

    steps:
      - uses: actions/checkout@v4

      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: latest
          files: |
            .\builds\script\spotifyimmersive_tampermonkey.js
            .\builds\extension\spotifyimmersive-latest.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
