name: Upload Release Assets

permissions:
  contents: write  # Allow the action to create releases and upload assets
  id-token: write  # Necessary for certain authentication processes
  actions: read    # Allow reading action logs and details

on:
  push: 
    tags:
      - 'latest'  # only for tags like v1.0.0, v2.1, etc.

jobs:
  upload-assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Assets
        run: |
          mkdir output
          echo "Release files" > output/info.txt

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            builds/script/spotifyimmersive_tampermonkey.js
            builds/extension/spotifyimmersive-latest.xpi
              
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
